# Single akun
# reformat di : sub.bonds.id
# Akun Vless CF (No UDP)
# =========== PROXY ACCOUNT ===========
proxies:
  - name: ID LINKGO XUTS ðŸ‡®ðŸ‡©
    server: 104.18.214.235
    port: 443
    type: vmess
    uuid: b61dff52-5593-4299-ad07-473fa7112ac9
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.linkgo.jbrs.cloud
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: ava.game.naver.com.linkgo.jbrs.cloud
    udp: true
  - name: ID1-XUTS ðŸ‡®ðŸ‡©
    server: 104.18.214.235
    port: 443
    type: vless
    uuid: fccdaaae-af39-41a7-9fde-fd32a48278cf
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.aio.skibidicx.web.id
    network: ws
    ws-opts:
      path: /ID1
      headers:
        Host: ava.game.naver.com.aio.skibidicx.web.id
    udp: true
  - name: ID2-XUTS ðŸ‡®ðŸ‡©
    server: 104.18.214.235
    port: 443
    type: vless
    uuid: aaaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.free.vpn-wuss.BIZ.id
    network: ws
    ws-opts:
      path: /Free/TG-at-BitzBlack/43.218.77.16-1443
      headers:
        Host: ava.game.naver.com.free.vpn-wuss.BIZ.id
    udp: true

